import numpy as np

a = np.zeros((10, 2))
print("a---------------------")
print(a)
print("a.T---------------------")   # a.T = np.zeroa((2,10))
b = a.T
print("b---------------------")
print(b)
print("c---------------------")
c = b.view()
print(c)
d = np.reshape(b, (5, 4))
e = np.reshape(b, (20,))
f = np.reshape(b, (20, 1))
g = np.reshape(b, (-1, 20))
print("shape---------------------")
print(d.shape, e.shape, f.shape, g.shape)
print("d---------------------")
print(d)
print("e---------------------")
print(e)
print("f---------------------")
print(f)
print("g---------------------")
print(g)
